organization: # all relative to $DATA_DIR
  features_dir: "features/"
  metadata: "layers.csv"
  model: "model_best.pt"
  splits: "splits_0.9-train.csv"
  xy: "Xy.csv"
train:
  batch_size: 64
  checkpoint: null
  factor: 0.5
  lr: 0.00005
  model: "vae"
  n_epochs: 100
  p_in: 3
  patience: 20
  save_every: 50
  save_subset: 2000
  z_dim: 128
bootstrap:
  path: "bootstraps_0.9-train.csv"
  index: null
  B: 100
