organization: # all relative to $DATA_DIR
  features_dir: "features/"
  model: "widenet.pt"
  xy: "Xy.csv"
  splits: "Xy.csv"
  metadata: "layers.csv"
train:
  model: "rcf"
  batch_size: 128
  n_patches: 256
  save_subset: 2000
  alpha: 0.1 # elastic net regularization parameter
  l1_ratio: 0.1 # mixing parameter l1 vs l2
bootstrap:
  path: "bootstraps_0.5-train.csv"
  B: 100
