organization: # all relative to $DATA_DIR
  features_dir: "features/"
  model: "model_best.pt"
  xy: "Xy.csv"
  splits: "Xy.csv"
  metadata: "layers.csv"
train:
  batch_size: 64
  checkpoint: null
  factor: 0.5
  lr: 0.0001
  model: "cnn"
  momentum: 0.9
  n_epochs: 100
  p_in: 7
  patience: 5
  save_every: 50
  save_subset: 2000
  nf: 16
bootstrap:
  path: "bootstraps_0.5-train.csv"
  B: 100
